# Generated by Django 2.2.28 on 2025-01-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('pfam_id', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ensembl_id', models.CharField(max_length=20)),
                ('gene_symbol', models.CharField(db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NeaseSavedRun',
            fields=[
                ('run_id', models.CharField(db_index=True, max_length=36, primary_key=True, serialize=False)),
                ('saved_for_days', models.IntegerField()),
                ('timestamp_of_creation', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(default='', max_length=255)),
                ('custom_name', models.CharField(default='', max_length=255)),
                ('organism', models.CharField(default='', max_length=255)),
                ('input_format', models.CharField(default='', max_length=255)),
                ('predicted_DDIs', models.CharField(default='', max_length=255)),
                ('p_value_cutoff', models.FloatField(default=0.05)),
                ('min_delta', models.FloatField(default=0.1)),
                ('majiq_confidence', models.FloatField(default=0.95)),
                ('only_ddis', models.BooleanField(default=False)),
                ('remove_not_in_frame', models.BooleanField(default=True)),
                ('only_divisible_by_three', models.BooleanField(default=False)),
            ],
        ),
    ]
