# Generated by Django 2.2.28 on 2024-09-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('pfam_id', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ensembl_id', models.CharField(max_length=20)),
                ('gene_symbol', models.CharField(db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NeaseSaveLocationMapping',
            fields=[
                ('run_id', models.CharField(db_index=True, max_length=36, primary_key=True, serialize=False)),
                ('saved_for_days', models.IntegerField()),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
