# Generated by Django 2.2.28 on 2024-09-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_neasesavelocationmapping_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neasesavelocationmapping',
            name='name',
        ),
        migrations.AddField(
            model_name='neasesavelocationmapping',
            name='custom_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='neasesavelocationmapping',
            name='file_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
