# Generated by Django 2.2.28 on 2024-11-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_auto_20240910_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeaseSavedRun',
            fields=[
                ('run_id', models.CharField(db_index=True, max_length=36, primary_key=True, serialize=False)),
                ('saved_for_days', models.IntegerField()),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(default='', max_length=255)),
                ('custom_name', models.CharField(default='', max_length=255)),
                ('organism', models.CharField(default='', max_length=255)),
                ('input_format', models.CharField(default='', max_length=255)),
                ('predicted_DDIs', models.CharField(default='', max_length=255)),
                ('p_value_cutoff', models.FloatField(default=0.05)),
                ('min_delta', models.FloatField(default=0.1)),
                ('majiq_confidence', models.FloatField(default=0.95)),
                ('only_ddis', models.BooleanField(default=False)),
                ('remove_not_in_frame', models.BooleanField(default=True)),
                ('only_divisible_by_three', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='NeaseSaveLocationMapping',
        ),
    ]
