# Generated by Django 2.2.28 on 2024-11-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_auto_20241119_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='neasesavedrun',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
