# Generated by Django 2.2.28 on 2024-11-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_neasesavedrun_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neasesavedrun',
            old_name='date_of_creation',
            new_name='timestamp_of_creation',
        ),
        migrations.RemoveField(
            model_name='neasesavedrun',
            name='timestamp',
        ),
    ]
